
services:
  app:
    container_name: app
    volumes:
      -  /home/icqparty/vscode/golang-example/config.yaml:/root/config.yaml:ro
    build: .
    # command: ./main
    ports:
      - "8081:8081"
