apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "golang-example.fullname" . }}
  annotations: 
    cert-manager.io/issuer: "letsencrypt-staging-ge"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - {{ .Values.host}}
    secretName: {{ .Values.ssl.secret}}
  rules:
  - host: {{ .Values.host}}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: golang-example
            port:
              number: 80